#################################################
# Nomad Containers Playbooks
#################################################
---
- hosts: workernodes
  vars_files:
    - ../vars/vars.yml

  tasks: 
    - name: create gatewayfm-erigon job
      community.general.nomad_job:
        host: localhost
        content_format: hcl
        force_start : true
        state: present
        content: "{{ lookup('ansible.builtin.file', '../nomad-jobs/gatewayfm-erigon-image.hcl') }}"
        timeout: 120
        use_ssl: no
        validate_certs: no
      tags:
        - erigon_nomad_job
        
    
    
    