---
  - hosts: workernodes
    vars_files:
      - ../vars/vars.yml

    tasks:
      ## Mounting Volume on the host machine, Supposing that we are working on EC2 ubuntu machine with only root volume
      - name: Ansible check directory.
        stat:
          path: /{{ volume_mount_dir }}
        register: volume_status
        tags: 
          - VolumeMount
      - name: "echo if directory already existed"
        debug:
          msg: "Mounted directory is already existed"
        when: volume_status.stat.exists
        tags: 
          - VolumeMount

      - name: "Ansible Create directory if not exists"
        file:
          path: /{{ volume_mount_dir }}
          state: directory
          mode: 0755
          group: root
          owner: root
        when: volume_status.stat.exists == false
        tags: 
          - VolumeMount
      - name: Format EBS Volume
        command: mkfs -t ext4 {{ volume_path }} 
        when: volume_status.stat.exists == false
        tags: 
          - VolumeMount
      - name: Mount EBS Volume
        command: mount {{ volume_path }} /{{ volume_mount_dir }}
        ignore_errors: yes
        tags: 
          - VolumeMount

      - name: Update Hostnames
        hostname:
          name: "{{ new_hostname }}"
        tags: 
          - hostname
      - name: Add hostname to /etc/hosts
        lineinfile:
          path: /etc/hosts
          regexp: '^127\.0\.0\.1[ \t]+localhost'
          line: '127.0.0.1 localhost {{ new_hostname }}'
          state: present
        tags: 
          - hostname

      - name: Install nomad if not exist on the remote node
        script: ../scripts/install-nomad.sh
        args:
          creates: /install-nomad.sh
        register: nomad_status
        tags: 
          - nomad
      
      - name: Upload nomad agent config file
        copy:
          src: ../templates/nomad.hcl
          dest: "{{ nomad_agent_config }}"
          mode: 0755

      - name: Configure Nomad Service
        template:
          src: ../templates/nomad.service.j2
          dest: /etc/systemd/system/nomad.service
          owner: root
          group: root
          mode: 0755
        notify: 
          - RetartNOMAD
        tags: 
          - nomad
        
      - name: Debug Status
        debug:
          msg: 
            - "{{ nomad_status }}"
        tags: 
          - nomad

      - name: EnableNOMAD Systemd Service
        systemd:
          name: nomad
          enabled: yes
          state: started
        when: nomad_status
        tags: 
          - nomad

      - name: Install python-nomad
        pip:
          name: python-nomad
        tags: 
          - nomad
          
      - name: Install Docker
        script: ../scripts/install-docker.sh
        args:
          creates: /install-docker.sh
        register: install_docker
        tags: 
          - docker
    
      - name: debug docker install
        debug:
          msg: "{{install_docker}}"
        tags: 
          - docker

    handlers:
      - name: RetartNOMAD
        service: name=nomad state=restarted
        tags: 
          - nomad
      
      